org: hashamorg
app: learnserverlessframework
service: ServerlessFrameWork

provider:
  name: aws
  runtime: nodejs20.x


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
